name: Deploy to WebSpaceKit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy-frontend:
    name: Upload FRONTEND → public_html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy FRONTEND
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: strict
          local-dir: FRONTEND
          server-dir: ${{ secrets.FTP_FRONTEND_DIR }}
          exclude: |
            **/.git**
            **/.github**
            **/node_modules**
            **/*.md
            database.sql
          state-name: .ftp-deploy-frontend-state.json
          dangerous-clean-slate: false
          log-level: standard

  deploy-api:
    name: Upload api → public_html/api
    needs: deploy-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy API
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: strict
          local-dir: api
          server-dir: ${{ secrets.FTP_API_DIR }}
          exclude: |
            **/.git**
            **/.github**
            **/node_modules**
          state-name: .ftp-deploy-api-state.json
          dangerous-clean-slate: false
          log-level: standard

